### ISSUE TITLE
Error: Cannot find module 'npm'

### ISSUE THREAD

**Issue by vaibhavjn** [blitzrk/libsass-build-sublime#2]
On Sublime Text 3 in Windows 7, when I installed this package, It throws the following error
![error](https://cloud.githubusercontent.com/assets/8787999/8801520/04233b94-2fd9-11e5-9edd-672025038ebf.jpg)

Path of node_modules in my system is : -
C:\Program Files\nodejs\node_modules

I set the path like this in libsass.sublime-build file :- 

{
    "cmd": [
    	"node",
    	"$packages/libsass-build-sublime/build.js",
    	"$file",
    	"$packages/User/LibSassBuild.sublime-settings"
	],
    "working_dir": "$file_path",
    "selector": "source.scss, source.sass",
    "windows": { "path": "C:/Program Files/nodejs/node_modules" },
    "osx": { "path": "/usr/local/bin:$PATH" }
}

After this, when I compiled the scss file after restarting Sublime Text 3, I got the below error :- 

[WinError 2] The system cannot find the file specified
[cmd: ['node', 'C:\\Users\\Vaibhav\\AppData\\Roaming\\Sublime Text 3\\Packages/libsass-build-sublime/build.js', 'Z:\\web2\\web\\app-web\\app\\styles\\_header.scss', 'C:\\Users\\Vaibhav\\AppData\\Roaming\\Sublime Text 3\\Packages/User/LibSassBuild.sublime-settings']]
[dir: Z:\web2\web\app-web\app\styles]
[path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\Skype\Phone\;C:\Ruby22-x64\bin;C:\Program Files\nodejs\;C:\Program Files\nodejs\node_modules\;C:\Users\Vaibhav\AppData\Roaming\npm]
[Finished]

![error2](https://cloud.githubusercontent.com/assets/8787999/8801700/310ec000-2fda-11e5-9a16-161da690293f.jpg)

Can anyone please help in sorting this out ?

**Comment by blitzrk** [comment]
Oh hey, someone's actually using this! I guess I should look at it again and start maintaining it. :)

Can you try doing `npm install -g npm`? If I just forgot that dependency, I'll add it to the config.

**Comment by vaibhavjn** [comment]
There is no Libsass build package for sublime besides this 
You have done a good job by building it 

I tried to do what you told but still its shows the same last error as showing in previous post screenshots. Please have a look at node js command prompt screenshot :- 

![node](https://cloud.githubusercontent.com/assets/8787999/8802701/d28b8912-2fe0-11e5-96a9-35037292d9c5.jpg)

**Comment by blitzrk** [comment]
Hmm... Well, since it installed correctly but is still erroring, I'll have to test it myself when I get home. I haven't tried it on Windows with Node 0.12,yet. Should be fixed in ~12 hours, but if you figure it out before then, feel free to submit a PR.

**Comment by blitzrk** [comment]
Alright, so installing node-sass on Windows is non-trivial. You need the right version of .NET and VS depending on the node-sass release. Sometimes Python 2, also. So I'm going to have to rewrite this for Windows, possibly without Node, in order to minimize dependencies or add a lot of messages. But I definitely will work on this.

In the meantime, you can try to get this working this way...

```
cd /c/Users/[User]/AppData/Roaming/Sublime\ Text\ 3/Packages/libsass-build-sublime
npm i -S npm
npm un -S node-sass
npm i
PYTHON=/c/Python27/python.exe npm i -S node-sass@0.9.3
```

Then install Visual Studio and whatever else it asks for. Untested, because my VM doesn't have the space for a VS install, but that might work.

I'll close this for now and make a new one for WIndows support.

**Comment by blitzrk** [comment]
My implementation was shortsighted. I've decided to completely rewrite this project so that node isn't needed at all. I should have something working within a week. I'll update this issue when it's done.

It will have no external dependencies, require less config, and be installable with PackageControl.

**Comment by blitzrk** [comment]
It took over 2 weeks to get merged into PackageControl, but if you're still looking for something like this, check out "Libsass Build", which is now in the public repository.

**Comment by vaibhavjn** [comment]
Thanks for reworking on it. Really appreciate the work you did.
I tried it.

But there are few issues and suggestions that I got :-

Issues :- 
1. When I try to edit .libsass.json, rather than overwriting the existing file, it saves it as a new file in a location defined by us. But rather than taking the new file, it still takes the old one, It should be like that it should overwrite the existing one or have .user and .default files like other packages.
2. It is creating a build folder every time a partial file is compiled which should not happen. Partial files should be avoided from compiling .
3. When a partial file is edited and saved, it should compile only those SCSS files in which that partial is included which is not happening right now. 
As a result, making changes in partial file later will not reflect those changes in the scss filess in which it is included. Changes reflect only when we compile the main scss files in which they are included.
4. Error messages not coming while compiling partial files.


Suggestions :- 
1. Rather than showing alert box every time, it will be better if you show the errors or even successful compilation messages in console just like sass build. Alert boxes coming while coding is not good. Have to close them everytime.

I am attaching the screenshot of a folder structure that is getting this issues.

![scss-structure](https://cloud.githubusercontent.com/assets/8787999/13196318/b441f78a-d7f0-11e5-9f1c-961723d988c4.jpg)

In both landing.scss and common.scss, I have included partial file just for testing.

Can you please have a look ?
